### ISSUE TITLE
any way to make it work on nextjs ?

### ISSUE THREAD

**Issue by mfaizan1** [xxxzeus/react-swipezor#3]
i imported and used this as described in docs 

but got this error. 

`ReferenceError: document is not defined
    at s (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:3572)
    at m (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:4813)
    at u (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:3511)
    at e.exports (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:5145)
    at Object.<anonymous> (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:2771)
    at n (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:124)
    at Module.<anonymous> (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:10706)
    at n (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:124)
    at /Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:923
    at Object.<anonymous> (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:932)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
ReferenceError: document is not defined
    at s (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:3572)
    at m (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:4813)
    at u (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:3511)
    at e.exports (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:5145)
    at Object.<anonymous> (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:2771)
    at n (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:124)
    at Module.<anonymous> (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:10706)
    at n (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:124)
    at /Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:923
    at Object.<anonymous> (/Users/faizanulhaq/Documents/react/ewana/node_modules/react-swipezor/build/index.js:1:932)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
`

i think this is because server side rendering.

**Comment by mmrahmad** [comment]
Same Problem
